# Generated by Django 2.0.2 on 2018-02-27 20:09

from django.db import migrations, models
import user.models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180227_1424'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[user.validator.check_decimal]),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(max_length=15, validators=[user.validator.validate_inn]),
        ),
    ]
